// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.2
// source: api/hvxahv/v1alpha1/channel.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewChannelData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Bio       string `protobuf:"bytes,3,opt,name=bio,proto3" json:"bio,omitempty"`
	Avatar    string `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Owner     string `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	IsPrivate bool   `protobuf:"varint,6,opt,name=isPrivate,proto3" json:"isPrivate,omitempty"`
}

func (x *NewChannelData) Reset() {
	*x = NewChannelData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_hvxahv_v1alpha1_channel_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewChannelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewChannelData) ProtoMessage() {}

func (x *NewChannelData) ProtoReflect() protoreflect.Message {
	mi := &file_api_hvxahv_v1alpha1_channel_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewChannelData.ProtoReflect.Descriptor instead.
func (*NewChannelData) Descriptor() ([]byte, []int) {
	return file_api_hvxahv_v1alpha1_channel_proto_rawDescGZIP(), []int{0}
}

func (x *NewChannelData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NewChannelData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewChannelData) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *NewChannelData) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *NewChannelData) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *NewChannelData) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

type NewChannelReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Id      string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *NewChannelReply) Reset() {
	*x = NewChannelReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_hvxahv_v1alpha1_channel_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewChannelReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewChannelReply) ProtoMessage() {}

func (x *NewChannelReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_hvxahv_v1alpha1_channel_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewChannelReply.ProtoReflect.Descriptor instead.
func (*NewChannelReply) Descriptor() ([]byte, []int) {
	return file_api_hvxahv_v1alpha1_channel_proto_rawDescGZIP(), []int{1}
}

func (x *NewChannelReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *NewChannelReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *NewChannelReply) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type NewChanAdmData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Id    string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Admin string `protobuf:"bytes,3,opt,name=admin,proto3" json:"admin,omitempty"`
}

func (x *NewChanAdmData) Reset() {
	*x = NewChanAdmData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_hvxahv_v1alpha1_channel_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewChanAdmData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewChanAdmData) ProtoMessage() {}

func (x *NewChanAdmData) ProtoReflect() protoreflect.Message {
	mi := &file_api_hvxahv_v1alpha1_channel_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewChanAdmData.ProtoReflect.Descriptor instead.
func (*NewChanAdmData) Descriptor() ([]byte, []int) {
	return file_api_hvxahv_v1alpha1_channel_proto_rawDescGZIP(), []int{2}
}

func (x *NewChanAdmData) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *NewChanAdmData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NewChanAdmData) GetAdmin() string {
	if x != nil {
		return x.Admin
	}
	return ""
}

type NewChanAdmReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *NewChanAdmReply) Reset() {
	*x = NewChanAdmReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_hvxahv_v1alpha1_channel_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewChanAdmReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewChanAdmReply) ProtoMessage() {}

func (x *NewChanAdmReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_hvxahv_v1alpha1_channel_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewChanAdmReply.ProtoReflect.Descriptor instead.
func (*NewChanAdmReply) Descriptor() ([]byte, []int) {
	return file_api_hvxahv_v1alpha1_channel_proto_rawDescGZIP(), []int{3}
}

func (x *NewChanAdmReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *NewChanAdmReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_hvxahv_v1alpha1_channel_proto protoreflect.FileDescriptor

var file_api_hvxahv_v1alpha1_channel_proto_rawDesc = []byte{
	0x0a, 0x21, 0x61, 0x70, 0x69, 0x2f, 0x68, 0x76, 0x78, 0x61, 0x68, 0x76, 0x2f, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x15, 0x68, 0x76, 0x78, 0x61, 0x68, 0x76, 0x2e, 0x76, 0x31, 0x61, 0x6c,
	0x70, 0x68, 0x61, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x92, 0x01, 0x0a, 0x0e, 0x4e,
	0x65, 0x77, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x62, 0x69, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6f,
	0x77, 0x6e, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65,
	0x72, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x73, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x69, 0x73, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x22,
	0x4f, 0x0a, 0x0f, 0x4e, 0x65, 0x77, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x4c, 0x0a, 0x0e, 0x4e, 0x65, 0x77, 0x43, 0x68, 0x61, 0x6e, 0x41, 0x64, 0x6d, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x64, 0x6d, 0x69,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x22, 0x3f,
	0x0a, 0x0f, 0x4e, 0x65, 0x77, 0x43, 0x68, 0x61, 0x6e, 0x41, 0x64, 0x6d, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32,
	0xcc, 0x01, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x5d, 0x0a, 0x0a, 0x4e,
	0x65, 0x77, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x25, 0x2e, 0x68, 0x76, 0x78, 0x61,
	0x68, 0x76, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4e, 0x65, 0x77, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x44, 0x61, 0x74, 0x61,
	0x1a, 0x26, 0x2e, 0x68, 0x76, 0x78, 0x61, 0x68, 0x76, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x65, 0x77, 0x43, 0x68, 0x61, 0x6e,
	0x6e, 0x65, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x62, 0x0a, 0x0f, 0x4e, 0x65,
	0x77, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x25, 0x2e,
	0x68, 0x76, 0x78, 0x61, 0x68, 0x76, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x65, 0x77, 0x43, 0x68, 0x61, 0x6e, 0x41, 0x64, 0x6d,
	0x44, 0x61, 0x74, 0x61, 0x1a, 0x26, 0x2e, 0x68, 0x76, 0x78, 0x61, 0x68, 0x76, 0x2e, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x65, 0x77,
	0x43, 0x68, 0x61, 0x6e, 0x41, 0x64, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x37,
	0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x69, 0x73,
	0x69, 0x73, 0x6d, 0x2f, 0x68, 0x76, 0x78, 0x61, 0x68, 0x76, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x68,
	0x76, 0x78, 0x61, 0x68, 0x76, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_hvxahv_v1alpha1_channel_proto_rawDescOnce sync.Once
	file_api_hvxahv_v1alpha1_channel_proto_rawDescData = file_api_hvxahv_v1alpha1_channel_proto_rawDesc
)

func file_api_hvxahv_v1alpha1_channel_proto_rawDescGZIP() []byte {
	file_api_hvxahv_v1alpha1_channel_proto_rawDescOnce.Do(func() {
		file_api_hvxahv_v1alpha1_channel_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_hvxahv_v1alpha1_channel_proto_rawDescData)
	})
	return file_api_hvxahv_v1alpha1_channel_proto_rawDescData
}

var file_api_hvxahv_v1alpha1_channel_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_hvxahv_v1alpha1_channel_proto_goTypes = []interface{}{
	(*NewChannelData)(nil),  // 0: hvxahv.v1alpha1.proto.NewChannelData
	(*NewChannelReply)(nil), // 1: hvxahv.v1alpha1.proto.NewChannelReply
	(*NewChanAdmData)(nil),  // 2: hvxahv.v1alpha1.proto.NewChanAdmData
	(*NewChanAdmReply)(nil), // 3: hvxahv.v1alpha1.proto.NewChanAdmReply
}
var file_api_hvxahv_v1alpha1_channel_proto_depIdxs = []int32{
	0, // 0: hvxahv.v1alpha1.proto.Channel.NewChannel:input_type -> hvxahv.v1alpha1.proto.NewChannelData
	2, // 1: hvxahv.v1alpha1.proto.Channel.NewChannelAdmin:input_type -> hvxahv.v1alpha1.proto.NewChanAdmData
	1, // 2: hvxahv.v1alpha1.proto.Channel.NewChannel:output_type -> hvxahv.v1alpha1.proto.NewChannelReply
	3, // 3: hvxahv.v1alpha1.proto.Channel.NewChannelAdmin:output_type -> hvxahv.v1alpha1.proto.NewChanAdmReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_hvxahv_v1alpha1_channel_proto_init() }
func file_api_hvxahv_v1alpha1_channel_proto_init() {
	if File_api_hvxahv_v1alpha1_channel_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_hvxahv_v1alpha1_channel_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewChannelData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_hvxahv_v1alpha1_channel_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewChannelReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_hvxahv_v1alpha1_channel_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewChanAdmData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_hvxahv_v1alpha1_channel_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewChanAdmReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_hvxahv_v1alpha1_channel_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_hvxahv_v1alpha1_channel_proto_goTypes,
		DependencyIndexes: file_api_hvxahv_v1alpha1_channel_proto_depIdxs,
		MessageInfos:      file_api_hvxahv_v1alpha1_channel_proto_msgTypes,
	}.Build()
	File_api_hvxahv_v1alpha1_channel_proto = out.File
	file_api_hvxahv_v1alpha1_channel_proto_rawDesc = nil
	file_api_hvxahv_v1alpha1_channel_proto_goTypes = nil
	file_api_hvxahv_v1alpha1_channel_proto_depIdxs = nil
}
