// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.3
// source: api/device/v1alpha1/device.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewDeviceAccountID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
}

func (x *NewDeviceAccountID) Reset() {
	*x = NewDeviceAccountID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_device_v1alpha1_device_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewDeviceAccountID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewDeviceAccountID) ProtoMessage() {}

func (x *NewDeviceAccountID) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_v1alpha1_device_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewDeviceAccountID.ProtoReflect.Descriptor instead.
func (*NewDeviceAccountID) Descriptor() ([]byte, []int) {
	return file_api_device_v1alpha1_device_proto_rawDescGZIP(), []int{0}
}

func (x *NewDeviceAccountID) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type NewDeviceID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *NewDeviceID) Reset() {
	*x = NewDeviceID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_device_v1alpha1_device_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewDeviceID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewDeviceID) ProtoMessage() {}

func (x *NewDeviceID) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_v1alpha1_device_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewDeviceID.ProtoReflect.Descriptor instead.
func (*NewDeviceID) Descriptor() ([]byte, []int) {
	return file_api_device_v1alpha1_device_proto_rawDescGZIP(), []int{1}
}

func (x *NewDeviceID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type NewDeviceCreate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Ua        string `protobuf:"bytes,2,opt,name=ua,proto3" json:"ua,omitempty"`
	Hash      string `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *NewDeviceCreate) Reset() {
	*x = NewDeviceCreate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_device_v1alpha1_device_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewDeviceCreate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewDeviceCreate) ProtoMessage() {}

func (x *NewDeviceCreate) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_v1alpha1_device_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewDeviceCreate.ProtoReflect.Descriptor instead.
func (*NewDeviceCreate) Descriptor() ([]byte, []int) {
	return file_api_device_v1alpha1_device_proto_rawDescGZIP(), []int{2}
}

func (x *NewDeviceCreate) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *NewDeviceCreate) GetUa() string {
	if x != nil {
		return x.Ua
	}
	return ""
}

func (x *NewDeviceCreate) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type DeviceCreateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey string `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (x *DeviceCreateReply) Reset() {
	*x = DeviceCreateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_device_v1alpha1_device_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceCreateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceCreateReply) ProtoMessage() {}

func (x *DeviceCreateReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_v1alpha1_device_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceCreateReply.ProtoReflect.Descriptor instead.
func (*DeviceCreateReply) Descriptor() ([]byte, []int) {
	return file_api_device_v1alpha1_device_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceCreateReply) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type DeviceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Reply string `protobuf:"bytes,2,opt,name=reply,proto3" json:"reply,omitempty"`
}

func (x *DeviceReply) Reset() {
	*x = DeviceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_device_v1alpha1_device_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceReply) ProtoMessage() {}

func (x *DeviceReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_v1alpha1_device_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceReply.ProtoReflect.Descriptor instead.
func (*DeviceReply) Descriptor() ([]byte, []int) {
	return file_api_device_v1alpha1_device_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceReply) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DeviceReply) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type DeviceData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId  string `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Device     string `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
	Hash       string `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	PrivateKey string `protobuf:"bytes,5,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	PublicKey  string `protobuf:"bytes,6,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (x *DeviceData) Reset() {
	*x = DeviceData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_device_v1alpha1_device_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceData) ProtoMessage() {}

func (x *DeviceData) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_v1alpha1_device_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceData.ProtoReflect.Descriptor instead.
func (*DeviceData) Descriptor() ([]byte, []int) {
	return file_api_device_v1alpha1_device_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeviceData) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *DeviceData) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DeviceData) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *DeviceData) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *DeviceData) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type DevicesData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string        `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Devices []*DeviceData `protobuf:"bytes,2,rep,name=devices,proto3" json:"devices,omitempty"`
}

func (x *DevicesData) Reset() {
	*x = DevicesData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_device_v1alpha1_device_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DevicesData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevicesData) ProtoMessage() {}

func (x *DevicesData) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_v1alpha1_device_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevicesData.ProtoReflect.Descriptor instead.
func (*DevicesData) Descriptor() ([]byte, []int) {
	return file_api_device_v1alpha1_device_proto_rawDescGZIP(), []int{6}
}

func (x *DevicesData) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DevicesData) GetDevices() []*DeviceData {
	if x != nil {
		return x.Devices
	}
	return nil
}

type NewDeviceHash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *NewDeviceHash) Reset() {
	*x = NewDeviceHash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_device_v1alpha1_device_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewDeviceHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewDeviceHash) ProtoMessage() {}

func (x *NewDeviceHash) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_v1alpha1_device_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewDeviceHash.ProtoReflect.Descriptor instead.
func (*NewDeviceHash) Descriptor() ([]byte, []int) {
	return file_api_device_v1alpha1_device_proto_rawDescGZIP(), []int{7}
}

func (x *NewDeviceHash) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type IsDeviceExistReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsExist bool `protobuf:"varint,2,opt,name=is_exist,json=isExist,proto3" json:"is_exist,omitempty"`
}

func (x *IsDeviceExistReply) Reset() {
	*x = IsDeviceExistReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_device_v1alpha1_device_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsDeviceExistReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsDeviceExistReply) ProtoMessage() {}

func (x *IsDeviceExistReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_device_v1alpha1_device_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsDeviceExistReply.ProtoReflect.Descriptor instead.
func (*IsDeviceExistReply) Descriptor() ([]byte, []int) {
	return file_api_device_v1alpha1_device_proto_rawDescGZIP(), []int{8}
}

func (x *IsDeviceExistReply) GetIsExist() bool {
	if x != nil {
		return x.IsExist
	}
	return false
}

var File_api_device_v1alpha1_device_proto protoreflect.FileDescriptor

var file_api_device_v1alpha1_device_proto_rawDesc = []byte{
	0x0a, 0x20, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x15, 0x68, 0x76, 0x78, 0x61, 0x68, 0x76, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x33, 0x0a, 0x12, 0x4e, 0x65, 0x77,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x12,
	0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x1d,
	0x0a, 0x0b, 0x4e, 0x65, 0x77, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x54, 0x0a,
	0x0f, 0x4e, 0x65, 0x77, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x0e, 0x0a, 0x02, 0x75, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x75, 0x61, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68,
	0x61, 0x73, 0x68, 0x22, 0x32, 0x0a, 0x11, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x22, 0x37, 0x0a, 0x0b, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65,
	0x70, 0x6c, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0xa7, 0x01, 0x0a, 0x0a, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x22, 0x5e, 0x0a, 0x0b, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x3b, 0x0a,
	0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21,
	0x2e, 0x68, 0x76, 0x78, 0x61, 0x68, 0x76, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x23, 0x0a, 0x0d, 0x4e, 0x65,
	0x77, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x48, 0x61, 0x73, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x68,
	0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22,
	0x2f, 0x0a, 0x12, 0x49, 0x73, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x45, 0x78, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x73, 0x5f, 0x65, 0x78, 0x69, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x45, 0x78, 0x69, 0x73, 0x74,
	0x32, 0xac, 0x05, 0x0a, 0x07, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x5c, 0x0a, 0x07,
	0x49, 0x73, 0x45, 0x78, 0x69, 0x73, 0x74, 0x12, 0x24, 0x2e, 0x68, 0x76, 0x78, 0x61, 0x68, 0x76,
	0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4e, 0x65, 0x77, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x48, 0x61, 0x73, 0x68, 0x1a, 0x29, 0x2e,
	0x68, 0x76, 0x78, 0x61, 0x68, 0x76, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x73, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x45, 0x78,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x06, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x12, 0x26, 0x2e, 0x68, 0x76, 0x78, 0x61, 0x68, 0x76, 0x2e, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x65, 0x77,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x1a, 0x28, 0x2e, 0x68,
	0x76, 0x78, 0x61, 0x68, 0x76, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x68, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x42, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49,
	0x44, 0x12, 0x29, 0x2e, 0x68, 0x76, 0x78, 0x61, 0x68, 0x76, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x65, 0x77, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x1a, 0x22, 0x2e, 0x68,
	0x76, 0x78, 0x61, 0x68, 0x76, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x44, 0x61, 0x74, 0x61,
	0x22, 0x00, 0x12, 0x5c, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x42,
	0x79, 0x48, 0x61, 0x73, 0x68, 0x12, 0x24, 0x2e, 0x68, 0x76, 0x78, 0x61, 0x68, 0x76, 0x2e, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x65,
	0x77, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x48, 0x61, 0x73, 0x68, 0x1a, 0x21, 0x2e, 0x68, 0x76,
	0x78, 0x61, 0x68, 0x76, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x00,
	0x12, 0x67, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6c, 0x6c, 0x42, 0x79, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x29, 0x2e, 0x68, 0x76, 0x78, 0x61, 0x68,
	0x76, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4e, 0x65, 0x77, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x49, 0x44, 0x1a, 0x22, 0x2e, 0x68, 0x76, 0x78, 0x61, 0x68, 0x76, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x06, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x12, 0x22, 0x2e, 0x68, 0x76, 0x78, 0x61, 0x68, 0x76, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x65, 0x77, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x1a, 0x22, 0x2e, 0x68, 0x76, 0x78, 0x61, 0x68, 0x76,
	0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x60, 0x0a,
	0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x42, 0x79, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x48,
	0x61, 0x73, 0x68, 0x12, 0x24, 0x2e, 0x68, 0x76, 0x78, 0x61, 0x68, 0x76, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x65, 0x77, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x48, 0x61, 0x73, 0x68, 0x1a, 0x22, 0x2e, 0x68, 0x76, 0x78, 0x61,
	0x68, 0x76, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42,
	0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x76,
	0x78, 0x61, 0x68, 0x76, 0x2f, 0x68, 0x76, 0x78, 0x61, 0x68, 0x76, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_device_v1alpha1_device_proto_rawDescOnce sync.Once
	file_api_device_v1alpha1_device_proto_rawDescData = file_api_device_v1alpha1_device_proto_rawDesc
)

func file_api_device_v1alpha1_device_proto_rawDescGZIP() []byte {
	file_api_device_v1alpha1_device_proto_rawDescOnce.Do(func() {
		file_api_device_v1alpha1_device_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_device_v1alpha1_device_proto_rawDescData)
	})
	return file_api_device_v1alpha1_device_proto_rawDescData
}

var file_api_device_v1alpha1_device_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_device_v1alpha1_device_proto_goTypes = []interface{}{
	(*NewDeviceAccountID)(nil), // 0: hvxahv.v1alpha1.proto.NewDeviceAccountID
	(*NewDeviceID)(nil),        // 1: hvxahv.v1alpha1.proto.NewDeviceID
	(*NewDeviceCreate)(nil),    // 2: hvxahv.v1alpha1.proto.NewDeviceCreate
	(*DeviceCreateReply)(nil),  // 3: hvxahv.v1alpha1.proto.DeviceCreateReply
	(*DeviceReply)(nil),        // 4: hvxahv.v1alpha1.proto.DeviceReply
	(*DeviceData)(nil),         // 5: hvxahv.v1alpha1.proto.DeviceData
	(*DevicesData)(nil),        // 6: hvxahv.v1alpha1.proto.DevicesData
	(*NewDeviceHash)(nil),      // 7: hvxahv.v1alpha1.proto.NewDeviceHash
	(*IsDeviceExistReply)(nil), // 8: hvxahv.v1alpha1.proto.IsDeviceExistReply
}
var file_api_device_v1alpha1_device_proto_depIdxs = []int32{
	5, // 0: hvxahv.v1alpha1.proto.DevicesData.devices:type_name -> hvxahv.v1alpha1.proto.DeviceData
	7, // 1: hvxahv.v1alpha1.proto.Devices.IsExist:input_type -> hvxahv.v1alpha1.proto.NewDeviceHash
	2, // 2: hvxahv.v1alpha1.proto.Devices.Create:input_type -> hvxahv.v1alpha1.proto.NewDeviceCreate
	0, // 3: hvxahv.v1alpha1.proto.Devices.GetDevicesByAccountID:input_type -> hvxahv.v1alpha1.proto.NewDeviceAccountID
	7, // 4: hvxahv.v1alpha1.proto.Devices.GetDeviceByHash:input_type -> hvxahv.v1alpha1.proto.NewDeviceHash
	0, // 5: hvxahv.v1alpha1.proto.Devices.DeleteAllByAccountID:input_type -> hvxahv.v1alpha1.proto.NewDeviceAccountID
	1, // 6: hvxahv.v1alpha1.proto.Devices.Delete:input_type -> hvxahv.v1alpha1.proto.NewDeviceID
	7, // 7: hvxahv.v1alpha1.proto.Devices.DeleteByDeviceHash:input_type -> hvxahv.v1alpha1.proto.NewDeviceHash
	8, // 8: hvxahv.v1alpha1.proto.Devices.IsExist:output_type -> hvxahv.v1alpha1.proto.IsDeviceExistReply
	3, // 9: hvxahv.v1alpha1.proto.Devices.Create:output_type -> hvxahv.v1alpha1.proto.DeviceCreateReply
	6, // 10: hvxahv.v1alpha1.proto.Devices.GetDevicesByAccountID:output_type -> hvxahv.v1alpha1.proto.DevicesData
	5, // 11: hvxahv.v1alpha1.proto.Devices.GetDeviceByHash:output_type -> hvxahv.v1alpha1.proto.DeviceData
	4, // 12: hvxahv.v1alpha1.proto.Devices.DeleteAllByAccountID:output_type -> hvxahv.v1alpha1.proto.DeviceReply
	4, // 13: hvxahv.v1alpha1.proto.Devices.Delete:output_type -> hvxahv.v1alpha1.proto.DeviceReply
	4, // 14: hvxahv.v1alpha1.proto.Devices.DeleteByDeviceHash:output_type -> hvxahv.v1alpha1.proto.DeviceReply
	8, // [8:15] is the sub-list for method output_type
	1, // [1:8] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_device_v1alpha1_device_proto_init() }
func file_api_device_v1alpha1_device_proto_init() {
	if File_api_device_v1alpha1_device_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_device_v1alpha1_device_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewDeviceAccountID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_device_v1alpha1_device_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewDeviceID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_device_v1alpha1_device_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewDeviceCreate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_device_v1alpha1_device_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceCreateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_device_v1alpha1_device_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_device_v1alpha1_device_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_device_v1alpha1_device_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DevicesData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_device_v1alpha1_device_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewDeviceHash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_device_v1alpha1_device_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsDeviceExistReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_device_v1alpha1_device_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_device_v1alpha1_device_proto_goTypes,
		DependencyIndexes: file_api_device_v1alpha1_device_proto_depIdxs,
		MessageInfos:      file_api_device_v1alpha1_device_proto_msgTypes,
	}.Build()
	File_api_device_v1alpha1_device_proto = out.File
	file_api_device_v1alpha1_device_proto_rawDesc = nil
	file_api_device_v1alpha1_device_proto_goTypes = nil
	file_api_device_v1alpha1_device_proto_depIdxs = nil
}
